

services:
  server:
    env_file:
      - ./configs/.env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres-db
    networks:
      - sql-db

  postgres-db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - sql-db

volumes: 
  pg-data:

networks:
  sql-db:
    driver: bridge